version: '3.8'

services:
  db:
    image: postgres:15
    container_name: lifeline-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lifeline
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: lifeline-backend
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/lifeline?sslmode=disable
    depends_on:
      - db
    restart: on-failure:5

  frontend:
    build: ./frontend
    container_name: lifeline-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: on-failure:5

  bot:
    build: ./bot
    container_name: lifeline-bot
    environment:
      - TELEGRAM_BOT_TOKEN=8031510962:AAFx7relBmfwGKUs4eZuhZIbCIKqfl-Zq08
      - BACKEND_URL=http://backend:8080/api
    depends_on:
      - backend
    restart: on-failure:5

volumes:
  postgres_data:

networks:
  default:
    name: lifeline-network
